### PR TITLE
add bash completion

### PR DESCRIPTION
**Pull request by int9h**
added bash completion in tools/

### CODE REVIEW

**Comment by nodesocket** [comment]
Hi @int9h. Thanks for the PR. How is this bash completion script actually used if it lives in the `tools` dir?

**Comment by int9h** [comment]
on Arch Linux, you need to symlink it to /usr/share/bash-completion/completions/cryptr
`ln -s /path/to/cryptr/tools/cryptr-bash-completion.bash /usr/share/bash-completion/completions/cryptr`

**Comment by nodesocket** [comment]
Ok. Just thinking how to describe this new feature in the README.md? Maybe you have some ideas and can add to the this PR?

**Comment by nodesocket** [comment]
@int9h bump. Any ideas on my previous comment?

**Comment by int9h** [comment]
It's cross platform if you use bash as your shell. But there are differents where the bash.completion files are saved. I added this to `README.md`

**Comment by nodesocket** [comment]
Thanks. Merged in.

**Pull request merged**
